### ISSUE TITLE
New blog design

### ISSUE THREAD

**Issue by ngkhanhlinh** [travis-ci/travis-foundation#23]
Here's a first draft of the new blog design. What do you think? @anikalindtner @svenfuchs @lislis

**Version 1** (Patterned background)

![travis-foundation-ver-1-1](https://f.cloud.github.com/assets/4908043/1700693/a0dfd900-6029-11e3-86f3-7de36927e96c.jpg)

[No need to pay attention to the difference in pattern color, it should be more seamless in the live version.]

**Version 2** (Patterned background)

![travis-foundation-ver-2-1](https://f.cloud.github.com/assets/4908043/1700694/c2a87c7c-6029-11e3-8b56-e7db562af794.jpg)

**Version 3** (White background)

![travis-foundation-ver-5](https://f.cloud.github.com/assets/4908043/1700674/8cab3606-6028-11e3-9582-6c88b0f169d7.png)

All comments are welcome. :) <3

**Comment by anikalindtner** [comment]
we have a new design now! \o/ :sparkles:
