### ISSUE TITLE
Open Source Grant info page

### ISSUE THREAD

**Issue by anikalindtner** [travis-ci/travis-foundation#40]
We want to build a site where people can get all the infos about Open Source Grants and maybe (as a second step) also are able to sponsor right away. 

What we have for now is this: http://foundation.travis-ci.org/grants/ 

@lislis and @meatballhat are working on getting a page online. I'll provide some texts. What points do you think should roughly be covered on this new site?

**Comment by meatballhat** [comment]
- [ ] what is expected from donors?
- [ ] what donors can expect from the foundation?
- [ ] what donors can expect from {project}?

**Comment by lislis** [comment]
- [ ] what is even Open Source Grants (how does it work, what is the frame, what are requirements for people, projects, sponsors)

**Comment by anikalindtner** [comment]
@lislis @meatballhat I've crafted a first draft here: https://docs.google.com/document/d/1K3Ig-VjCCoNsPOOHgXtADoKAVJpPCsL-CiC76bBMTbM/edit?usp=sharing Can you work with that? I'm sure the texts will need a bit of updating, but that was basically what was in my mind. Also feedback for missing info / the text is appreciated!

**Comment by MariadeAnton** [comment]
@anikalindtner thanks for the draft :) I've posted a few suggestions and comments over the text

**Comment by lislis** [comment]
I did, too

**Comment by alicetragedy** [comment]
All of the info for the Open Source Grants is up, all that's missing now is possibilities to donate. Should we leave this issue open?

**Comment by lislis** [comment]
@alicetragedy I'd say open a new ticket and outline what requirements/expectations are for the donation option

**Comment by alicetragedy** [comment]
good point @lislis. thank you for your input!
