### ISSUE TITLE
Imprint missing from home page

### ISSUE THREAD

**Issue by lstoll** [travis-ci/travis-foundation#43]
The homepage has no link to [the imprint](http://foundation.travis-ci.org/imprint/), which it probably should have somewhere.

**Comment by lislis** [comment]
good point!

**Comment by rkh** [comment]
Also, VAT ID missing. And I think it should be `gUG` instead of `UG. @fritzek?

**Comment by lstoll** [comment]
Here we go I took a crack at doing @saltinejustine's job

![we are - travis foundation 2015-10-14 09-55-32](https://cloud.githubusercontent.com/assets/694/10485740/d0aaf3a6-7259-11e5-80f2-01707cb97981.png)

**Comment by rkh** [comment]
It's beautiful.

**Comment by saltinejustine** [comment]
@lstoll keep your day job...

**Comment by fritzek** [comment]
@rkh - the "gUG" isn't necessary - legally-wise - it only gives people a glimpse about the charitable status, but it is not wrong to add it

**Comment by rkh** [comment]
Yeah, right now it's not visible that we're a charitable organisation.

**Comment by saltinejustine** [comment]
@lislis @rkh this was brought up again in conversation yesterday. the lack of having it is potentially disrupting our ability to take donations. Let's get this fixed soonish?

**Comment by lislis** [comment]
@saltinejustine sure thing! Tell me where to put the link and @rkh and @fritzek tell me what to change and it will be up in no time.
This is the page in question again: btw http://foundation.travis-ci.org/imprint/

**Comment by fritzek** [comment]
Hey @lisa




Only thing I can see missing in Imprint is the VAT ID - here you go: DE295684024


—

**Comment by lislis** [comment]
@fritzek amazing! thanks!

**Comment by saltinejustine** [comment]
@lislis alrighty, so let's go with

a design like this — https://www.dropbox.com/s/vvx456jzw8e7coh/foundation-hotpink-css.png?dl=0

and here is the icon for that — https://www.dropbox.com/s/tdplp8bnnzoz34s/imprint-icon.svg?dl=0

**Comment by lislis** [comment]
Closed by 62c2372142e3e320ee24a76e042
thanks @saltinejustine

**Comment by saltinejustine** [comment]
Thank you @lislis!
