### ISSUE TITLE
Add a logo page 

### ISSUE THREAD

**Issue by anikalindtner** [travis-ci/travis-foundation#48]
We have a wonderful logo page for our travis-ci site: https://travis-ci.com/logo. Would be great to have something like this (can be super basic) for the Foundation. 

@saltinejustine wdyt? would you be up for that?

**Comment by saltinejustine** [comment]
@anikalindtner sure absolutely no problem!

**Comment by anikalindtner** [comment]
whoooop! :tada:

**Comment by anikalindtner** [comment]
btw @saltinejustine this has low priority, doesn't need to be done asap. so e.g. the diversity ticket thing would be a higher priority :)

**Comment by saltinejustine** [comment]
FYI: this is underway :+1: :sparkles:

**Comment by alicetragedy** [comment]
Closed with https://github.com/travis-ci/travis-foundation/pull/83
thank you so so much for this @lislis — and @ctrlaltjustine for your wonderful work with our logo.
