### ISSUE TITLE
Open Source Grants new background image

### ISSUE THREAD

**Issue by saltinejustine** [travis-ci/travis-foundation#53]
Hey @lislis I'm opening this issue so you can find the photo for the OSG we talked about today. @anikalindtner gave me a new photo and I've green-ified it. It can be found in the invision [project assets folder](https://projects.invisionapp.com/d/#/projects/4550250/assets/7278434) in the Foundation project.

**Comment by lislis** [comment]
lol, I was actually talking about still another image
![screen shot 2016-01-22 at 13 37 30](https://cloud.githubusercontent.com/assets/1006478/12510886/6bf22a8a-c10d-11e5-8155-8474715980da.png)
But I just cropped it myself :)

**Comment by saltinejustine** [comment]
@lislis ughhhh

![facepalm](https://media.giphy.com/media/Ci3NqgC2GfbXy/giphy.gif)

**Comment by alicetragedy** [comment]
we can close this, right? :)

**Comment by saltinejustine** [comment]
Yep!
