### ISSUE TITLE
Foundation Resources Page

### ISSUE THREAD

**Issue by acnagy** [travis-ci/travis-foundation#59]
We need a place to collect relevant external resources, articles, etc., to share with everyone for the foundation site. This idea of @anikalindtner's grew from @ffffux's awesome list of quotes and articles around issues such as diversity, priviledge, silencing, and other topics.

**Comment by alicetragedy** [comment]
thank you so much for creating the issue @acnagy!

The tasks I see for this to get done are:
- [ ] collecting resources
- [ ] separating them into topics (e.g. CoC, organising conferences, gender pay gap, inclusivity, etc..)
- [ ] creating the page on the site (I was thinking a single page for a show/hide functionality for each topic would be a good idea).

I think we can make collecting resources an ongoing task (maybe we just post links to interesting resources as a single, editable, comment in here); I can see the page looking similar to [this one](http://foundation.travis-ci.org/projects/), with the subheadings being the different categories/topic. 
If you think you'd like to tackle the creation/development of the page itself first, I think that's ok (and probably more exciting for you). We already have a ton of resources, so I think we can already have the following sections:
- Code of Conduct
- inclusivity
- organising conferences

**Comment by acnagy** [comment]
Awesome! Thanks so much for the notes - super exciting to get this started. 

Tasks make sense to me, though I agree, we might be all set for now with resources - so perhaps just categorizing them first and/or getting a sense of categories?

Sounds great to start with building the page first, especially based off of the projects page. One initial question though - I noticed the Projects page redirects it's topic links to a new page (e.g click "Rails Girls Summer of Code", and you end up here: http://foundation.travis-ci.org/projects/rgsoc/), rather than working as a sort of show/hide on the same page. I'm kinda partial to copying the structure for the Projects page more directly, for the sake of consistency, but I'd love to do whatever works best. @alicetragedy what sounds best to you? 

In any event, looking forward to getting started right away! :)

**Comment by alicetragedy** [comment]
Sorry for getting back to you so late!
I trust your expertise, so if you feel like, from a UI/UX point of view, it would be confusing to use the exact same look as the projects page and having the links do something different (e.g. show/hide instead of separate page) we can also create separate pages for each topic. That would work for me and support whichever decision you decide to go with. 
Alternatively, we could start by using the grants page (http://foundation.travis-ci.org/grants/) as a foundation, where each heading is a new topic with a little bit of text explaining the context and related resources listed underneath. If we see that we have too many resources eventually, we can switch to separate pages. wdyt?

**Comment by acnagy** [comment]
@alicetragedy No worries That's a great idea with the grants page. While we're still growing the list of resources, I agree that keeping it on one page is best, especially since it has the advantage of being an at-a-glance view of everything. Of course, once the resources list outgrows the one page (and I'm sure it will soon!), switching over to the projects page structure looks super straightforward. I'll go ahead with that structure and let you know when I have a version for you to check out. :)

**Comment by ffffux** [comment]
I'd like to add, just for reference, that ModelViewCulture started a resources page as well (you can find it [here](https://modelviewculture.com/resources)). It may be a good idea to link that, or so?

**Comment by acnagy** [comment]
Thanks, @ffffux! Really appreciate the reference - looks a lot like what we're going for (maybe a little long for one page though? that said, the table of contents is good). Also, agreed - I definitely think we should link to it under a "Diversity" section. @alicetragedy Sound right to you?

**Comment by alicetragedy** [comment]
@acnagy great, sticking to one page for now is good to me. also +1 on adding a link to the MVC resources page under "Diversity" or any other topic that seems more relevant.

**Comment by alicetragedy** [comment]
@anikalindtner I'd suggest to collect all resources we have in this issue, so that @acnagy has easy access to them as she's currently working on the page. wdyt?

**Comment by anikalindtner** [comment]
### Reverse discrimination 

(thanks to lena!)

+ http://www.hanselman.com/blog/OnPieChartDiversityAtTechnicalConferences.aspx
+ http://everydayfeminism.com/2015/01/reverse-oppression-cant-exist/
+ https://www.bustle.com/articles/71400-6-reasons-men-can-literally-never-be-victims-of-sexism-and-those-who-think-they

**Comment by anikalindtner** [comment]
(WIP) 

There is this amazing publicly available google doc folder with 60+ women in tech - studies and articles, that we should share in whole: 

https://drive.google.com/open?id=0B79UlI0LWGoAflBnV1k1UUxWdWlZNElZczRMeThHeTd0Z1RjQmJiN01lS2tFWTJyOVR3OG8

But I also think we can break down the topics a bit as well to make it easier to categorize these pdfs

Unconscious bias:

+ Unconscious Bias Theory in Employment Discrimination Litigation: https://drive.google.com/open?id=0B79UlI0LWGoAeTdibFVkUUhtV0U

+ Implicit bias: A Primer for Court https://drive.google.com/open?id=0B79UlI0LWGoARGdFTGIwYUQzQ1E 

+ Double Jeopardy Gender Bias Against Women of Color in Science: https://drive.google.com/open?id=0B79UlI0LWGoAeS1rRkQ0TmF3Xzg

+

**Comment by alicetragedy** [comment]
### Inclusivity at conferences

- A website that collects information about making conferences accessible and inclusive: http://ramp-up.me/

**Comment by acnagy** [comment]
@anikalindtner @alicetragedy Oh my goodness! So sorry I missed those resources - I'll get them added to the draft page by the end of the week.

**Comment by alicetragedy** [comment]
@acnagy seriously, don't worry about it and thanks for adding them in advance — I will try to compile a list of categories we will have by next week. thanks so much for your great work, I can't wait to have this online 😍

**Comment by alicetragedy** [comment]
@acnagy I've updated the main sections (for now) in my [original comment](https://github.com/travis-ci/travis-foundation/issues/59#issuecomment-231041971) based on the resources we've added in here. 

### Allyship
- [Guide to Allyship](http://www.guidetoallyship.com/)
- [Being an effective ally to women and non-binary people](https://codeascraft.com/2016/10/19/being-an-effective-ally-to-women-and-non-binary-people/)

**Comment by acnagy** [comment]
@alicetragedy Awesome! Thanks so much. I'll update the page and add these two resources as well. Also, I think I forgot [Model View Culture](https://modelviewculture.com/), so I'll add that one in somewhere as well. Will let you know when there's something to preview! 

In the meantime, please feel free to send any other changes 💖

**Comment by ffffux** [comment]
if you're interested, I can dig through my archives on the weekend and look for resources on the topics that Laura mentioned on the bottom of [this comment](https://github.com/travis-ci/travis-foundation/issues/59#issuecomment-231041971)? Or other topics, if you give me some pointers on what you think could be interessting? ✨

**Comment by acnagy** [comment]
@ffffux Sounds awesome to me! Thank you! I'm not sure if there are other topics lists being pulled together other than the one above, but I'd bet @alicetragedy will know. 

As to specific content, I haven't been picking it, but generaly articles/talks are reasonably detailed and have a combination of discussion and concrete action steps. But, again, I think Laura will know more about what components a potential outside resource should have.

**Comment by alicetragedy** [comment]
@ffffux I think that would be super if you had time to do so! I think important resources to have are basic, kind of "Feminism 101" sort of resources. Obviously we don't want to focus just on articles that offer basic information, but they're a good start. And as Anna suggested, ones that offer concrete steps are great too. 
I think having a section about "Gender" (the multiple facets of gender and gender as a spectrum rather than a "boolean value") would be really helpful as well, so if you have any resources on that topic, I'd love to have them in the list.

**Comment by alicetragedy** [comment]
Note: I've updated my original comment accordingly to include "Gender" as well.

**Comment by ffffux** [comment]
@acnagy @alicetragedy sounds good, thanks, you two! I'll try to dig up some content, will post before Tuesday next week.

**Comment by alicetragedy** [comment]
Under allyship:
[Tips for Allies of Transgender People](https://www.glaad.org/transgender/allies)

**Comment by alicetragedy** [comment]
### Gender Pay Gap
[Narrow the Gapp](http://narrowthegapp.com) — calculator to compare gender pay differences in different occupations and fields

**Comment by alicetragedy** [comment]
### Code of Conduct

[This](http://wunder.schoenaberselten.com/2016/02/17/should-my-tech-conference-community-have-a-code-of-conduct-recommended-resources/) is a resource that @ffffux shared with us in slack at some point — a list of resources, I think we could either link to the resource page directly (so meta!) or pick some resources we feel are really important. ✨

**Comment by alicetragedy** [comment]
I really love this resource 👉 [The Less Obvious Conference Checklist](https://github.com/erikr/lessobviouschecklist)
I'm not sure where exactly it could fit into our categories. Maybe inclusivity? I think it might be better than creating its own category (e.g. Conference Planning). wdyt @acnagy?

**Comment by alicetragedy** [comment]
closed in https://github.com/travis-ci/travis-foundation/pull/69 
the last resource linked to was added here: https://github.com/travis-ci/travis-foundation/pull/79

thanks so much @acnagy for all your work in getting this up and running ✨
